server:
  port: 8080

spring:
  application:
    name: upload-service
  config:
    import: optional:file:.env[.properties]

aws:
  s3:
    bucket: ${AWS_S3_BUCKET:publications}
    region: ${AWS_REGION:eu-east-1}
    access-key: ${AWS_ACCESS_KEY_ID:minioroot}
    secret-key: ${AWS_SECRET_ACCESS_KEY:minioroot}
    endpoint: http://localhost:9000