server:
  port: 8083
services:
  storage:
    url: http://localhost:8081/api/v1/publications
  metadata:
    url: http://localhost:8082/api/v1/publications

spring:
  application:
    name: aggregator-service
  config:
    import: optional:file:.env[.properties]

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs