server:
  port: 8086

spring:
  application:
    name: enhancement-service
  config:
    import: optional:file:.env

  ai:
    ollama:
      chat:
        model: ${CHAT_MODEL:deepseek-r1:1.5b}
        options:
          temperature: 0.7
          frequency-penalty: 0.5
          presence-penalty: 1
          max-tokens: 128000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs